// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlacesTravelled;

namespace PlacesTravelled.Migrations
{
    [DbContext(typeof(PlacesTravelledContext))]
    [Migration("20180927184831_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PlacesTravelled.DataModel.Locations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Note");

                    b.Property<string>("Place");

                    b.Property<int>("TimesVisited");

                    b.Property<bool>("WillIGoBack");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(2018, 9, 25, 14, 48, 29, 766, DateTimeKind.Local), Note = "Fancy Food", Place = "Taco Bell", TimesVisited = 1, WillIGoBack = true },
                        new { Id = 2, Date = new DateTime(2018, 9, 24, 14, 48, 29, 767, DateTimeKind.Local), Note = "Fancier Food", Place = "Burger King", TimesVisited = 1, WillIGoBack = true },
                        new { Id = 3, Date = new DateTime(2018, 9, 22, 14, 48, 29, 767, DateTimeKind.Local), Note = "Fancieset Food", Place = "Taco King", TimesVisited = 1, WillIGoBack = true }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
